### ISSUE TITLE
release on F-Droid

### ISSUE THREAD

**Issue by hex-m** [openHPI/xikolo-android#140]
Would you consider distributing you application via F-Droid? If so you may check out this [guide](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/). According to [exodus-privacy](https://reports.exodus-privacy.eu.org/en/reports/24921/) you would have to remove two trackers as proprietary libraries are prohibited by the F-Droid [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

**Comment by tobiasrohloff** [comment]
Unfortunately, we don't have the resources to maintain a built for F-Droid. We also use other Google Play Services APIs and the app currently doesn't work without them. Sorry.

You can build the app locally and sideload it on your device.

**Comment by Poussinou** [comment]
Hi @openHPI 
Would it be possible to attach the apk(s) in the [release](https://github.com/openHPI/xikolo-android/releases) section every time you tag a new version, it would allow people without the Play Store to download your apps from there?

**Comment by tobiasrohloff** [comment]
I don't think that's possible. The app uses Google Play Services APIs and is released with the [Android App Bundles](https://developer.android.com/guide/app-bundle) format. We don't build APKs anymore.
