### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by janrenz** [openHPI/xikolo-android#19]
for those platforms that support Channels

**Comment by rhlff** [comment]
@jprberlin what are channels?

**Comment by jprberlin** [comment]
Something like open.sap.com/channels/thought-leaders. Each channel has a custom color and name. 
I see three (low priority) action items here:
- Use different color per course 
- Access courses via channel
- View Channel Information

For all 3 we will need API extensions

**Comment by tobiasrohloff** [comment]
Channels are enabled on openSAP, OpenWHO and mooc.house so far. 

openHPI will be enabled later this year.

**Comment by tobiasrohloff** [comment]
I added a channel icon in https://github.com/openHPI/xikolo-android/commit/fba2dec4702cdbd8925698db1b144aef2c0b87f5
