### ISSUE TITLE
Make content of app available in device search

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-android#2]
Maybe start with course titles

**Comment by rhlff** [comment]
Needs to be done with webmaster:
https://support.google.com/googleplay/android-developer/answer/6041489#

**Comment by rhlff** [comment]
Still work in progress @jprberlin? Or can be closed?

**Comment by jprberlin** [comment]
Or is this available now?

**Comment by rhlff** [comment]
Now it's done for real.
