### ISSUE TITLE
Different start dates

### ISSUE THREAD

**Issue by jprberlin** [openHPI/xikolo-android#20]
Mit der neuen API V2 (/api/v2/courses) gibt es ein Anzeigedatum. Das soll für die Anzeige in der Liste verwendet werden. Für die Steuerung des Zugangs soll das normale startDate verwendet werden.

Bei Bedarf kann ich ein Kurs mit diesen Eigenschaften zur Verfügung stellen.

"startDate": "2015-11-11T09:00:00Z",
"endDate": "2015-12-09T09:30:00Z",
"displayStartDate": "2015-11-11T09:00:00Z"

**Comment by rhlff** [comment]
deprecated
