### ISSUE TITLE
Add jump-off points for additional external pages

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-android#207]
For each platform, there can be additional external pages - like microlearning or podcasts - which should be integrated into the apps. As of now, we can't receive any of the required data via the API. Therefore, the only option we have is to add jump-off points that link to the respective websites. 

As a first step, we should create a UI mockup of these jump-off points. For the android app, we are likely to include the additional points in the side drawer.
Please create a screenshot of the side drawer showing additional points for `Microlearning` and `Podcasts`.

**Comment by bengelhaupt** [comment]
I propose the following alternatives. I personally would go with option 2 or 3. I think it is important to convey that it is just a link.

<img src="https://user-images.githubusercontent.com/26904189/73217201-c1f15400-4157-11ea-8e9a-b27fdb70ff00.jpg" width="200px" /> <img src="https://user-images.githubusercontent.com/26904189/73217252-df262280-4157-11ea-947b-2d6a4d708bfd.jpg" width="200px" /> <img src="https://user-images.githubusercontent.com/26904189/73217698-b2263f80-4158-11ea-9712-8c9d43ed39b8.jpg" width="200px" /> <img src="https://user-images.githubusercontent.com/26904189/73217281-efd69880-4157-11ea-8c24-09aa366b4d27.jpg" width="200px" /> <img src="https://user-images.githubusercontent.com/26904189/73217337-0aa90d00-4158-11ea-8e30-1d1968d5f573.jpg" width="200px" />

**Comment by mathebox** [comment]
Thanks very much for these screenshots!
I personally like option 3.

I'm closing this issue for now. We can reopen it when we figured out the integration.

**Comment by mathebox** [comment]
The design for option 3 was approved. Therefore, I'm reopening this issue.
Feel free to implement this ;)

The respective links are:
- https://open.sap.com/microlearning
- https://open.sap.com/podcasts
