### ISSUE TITLE
Android App Shortcuts

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#209]
https://developer.android.com/guide/topics/ui/shortcuts

Let's discuss possible shortcut actions with @mathebox.

**Comment by mathebox** [comment]
Here is the respective issue for the iOS app: https://github.com/openHPI/xikolo-ios/issues/653

**Comment by tobiasrohloff** [comment]
iOS looks like this:
![photo_2020-02-25 13 31 56](https://user-images.githubusercontent.com/2922744/75247895-44ab1480-57d3-11ea-9eb8-8b6ad2415e18.jpeg)
