### ISSUE TITLE
Change title of helpdesk and add hint

### ISSUE THREAD

**Issue by chagedorn** [openHPI/xikolo-android#229]
For users, it is not clearly visible that the "Hilfe" / "Help" section is the technical user support. Accordingly, please change the title and add a short hint on the bottom of the page (before the submit button), so users know that they are contacting real people rather than searching for FAQ / using a search option:

- Change title:
   - EN: Technical Support
   - DE: Technischer Support
- Show Hint on bottom of page:
   - EN: You will create a ticket that will be answered by the helpdesk team.
   - DE: Mit Absenden wird ein Ticket erstellt, das von unserem Helpdesk-Team beantwortet wird.

In addition, please add the hints from web about FAQ and ticket language/certificate, so users can more easily find the FAQ in the apps as well.

**Comment by tobiasrohloff** [comment]
Only for OpenWHO or all brands?

**Comment by chagedorn** [comment]
All brands - the langugage/certificate hint is only shown on OpenWHO, but the FAQ link hint is on the other platforms as well (so all platforms have a more or less small hint).

**Comment by tobiasrohloff** [comment]
Where should users ask for non-technical support? The course forums? Should we guide them there?

**Comment by chagedorn** [comment]
The helpdesk is supposed to be just for technical questions - even though this might not be clear to everyone, so yes, the help widget should help users finding the help they need. 
Shouldn't this be covered in the FAQ? So more or less, this will be covered in the next ticket to integrate the chatbot to the apps as well (https://dev.xikolo.de/youtrack/issue/XI-4269), but it will take quite some time until it is implemented.
If you have any good idea how to improve the hints for better usability right now, we can discuss again with Max (hes currently having fun with the hints in general) and adapt the view accordingly.

**Comment by tobiasrohloff** [comment]
@chagedorn I adjusted the texts and changed the title but I've adapted your requirements and wording a bit to keep things simple and don't clutter the UI (e.g., there will be no bottom text). The brand-specific hint and FAQ link are still to-dos.

![Screenshot_1585580876](https://user-images.githubusercontent.com/2922744/77929671-39ec0f80-72aa-11ea-8216-38eab4835370.png)

**Comment by tobiasrohloff** [comment]
@chagedorn @cwillems I finished this similar to our iOS approach (thx @mathebox). Let me know if you have further feedback.

![Screenshot_1585905319](https://user-images.githubusercontent.com/2922744/78344471-b88fc800-759c-11ea-96ff-f050cb5c29a7.png)

**Comment by chagedorn** [comment]
In der Info-Box: Before writing a ticket to [**the**] technical support ... ?

Ansonsten gefällt es mir gut

**Comment by tobiasrohloff** [comment]
> In the Info-Box: Before writing a ticket to [**the**] technical support ... ?

Fixed.
