### ISSUE TITLE
Disallow enrollments in not enrollable courses

### ISSUE THREAD

**Issue by mathebox** [openHPI/xikolo-android#237]
[This course](https://mooc.house/courses/m40kb) (part of [this channel](https://mooc.house/channels/mittelstand-40-kompetenzzentrum-berlin)) is `accessible` but not `enrollable`.

- Users should not be able to enroll in theses courses via the app
- Users who are already enrolled in this course should be able to unenroll from theses courses via the app.

The web application hides the enrollment button and displays an additional info box. With the next release, the iOS app will have similar behavior.

Localizations for the infoxbox text:
- de: Sie benötigen eine Einladung, um sich für diesen Kurs einzuschreiben.
- en: You must be invited to enroll in this course.

**Comment by tobiasrohloff** [comment]
We should probably extend the infobox text with something like: 

>You must be invited to enroll in this course. If you have been invited, please enroll on the web platform, then you can also access the course in the app.

Open for other suggestions.

**Comment by mathebox** [comment]
@tobiasrohloff Do you know the process for course invitations? I guess it's achieved by special URLs. But are these URLs directly handle by the apps via deep linking? It the user automatically enrolled after clicking on the link?

**Comment by tobiasrohloff** [comment]
I have no idea about the whole feature.

**Comment by mathebox** [comment]
The strings from the web application are sufficient for now. No need to modify them.
