### ISSUE TITLE
Hide course dates menu item

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#241]
Only show the course dates menu icon in the action bar of a course, when there are actually course dates.

I thought we already fixed that, so this might be broken again?

**Comment by bengelhaupt** [comment]
In what course does this bug occur?

**Comment by tobiasrohloff** [comment]
In many old openSAP courses, e.g., "SAP Fiori for iOS - An Introduction", "SAP BW/4HANA in a Nutshell", or "Experience SAP Hybris Solutions".
