### ISSUE TITLE
Display Video Subtitles and Description also in Preview

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#252]
![Screenshot_20200604-093606](https://user-images.githubusercontent.com/2922744/83730092-df27b900-a648-11ea-88af-33032d467b64.png)

**Comment by tobiasrohloff** [comment]
Pros and Cons should be discussed with UI/UX.

**Comment by bengelhaupt** [comment]
How about having an expand toggle (⌄, downward chevron) at the right edge of the screen next to the title which inflates a container (with a slightly darker background) downwards including all or parts of the description?

**Comment by mathebox** [comment]
Since there is already a download button in the top bar, there is no need for a more advanced UI pattern and partially hiding the description.
The labels for the subtitles and the description can simply be inserted between the item title and the download section.

**Comment by tobiasrohloff** [comment]
The toolbar action starts the download for the whole section.

**Comment by mathebox** [comment]
Hm this is not really discoverable...
I would still argue that it's okay for the user to scroll to see the download section.
