### ISSUE TITLE
Improve Deep Link handling for Course

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#28]
When a Deep Link is handled for a course (see `CourseActivity`), all courses are fetched and the matching course is extracted. This can be improved by fetching directly the specific course, since we have access to the course code.

**Comment by rhlff** [comment]
@jprberlin the route `GET /api/courses/:course_id` (show course) seems offline for the api (500). Can we fix this easily? And is it possible to request courses with the `course_code` next to the `course_id` (404 at the moment)? Or is this too much of work for the old api?

**Comment by jprberlin** [comment]
why not use the new api here? There i could also add course code fetching..

**Comment by tobiasrohloff** [comment]
Fixed since version 2.
