### ISSUE TITLE
Cannot Open LTI Exercises

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#286]
Currently, it seems that opening LTI exercises don't work anymore. A toast message states that "an error occurred". The expected behavior is that a browser window is opened with the LTI exercise for the current user.

I tested it with the emulator and my Pixel 3, both run Android 11.

It could be a regression from the last deep link fixes.

Also, it should work with external LTI tools and inline LTI tools, which are rendered in an iframe for the web app. We don't differentiate the behavior on mobile here, both types are opened externally. I already tested the API responses and they work fine for both (and the API also shows the same behavior for both).

An external LTI exercise:
https://open.hpi.de/courses/ruby2018/items/3ILkiD5AIgbeX11ix3bQz0

An inline LTI exercise (hidden and invite-only test course):
https://open.hpi.de/courses/mwtest/items/6LETxwi26TLse5yjZ7hNYo

**Comment by tobiasrohloff** [comment]
@bengelhaupt I enrolled you already for the test course to test the inline LTI item. It won't show a whole lot due to a JS bug in the H5P tool, but should be sufficient. Also see https://dev.xikolo.de/youtrack/issue/XI-4583

**Comment by bengelhaupt** [comment]
I just tried to reproduce the bug on my OnePlus 7 Pro (Android 10) with the latest production version and it works as expected. Will test on an Android 11 Emulator later. Do you have both the debug and production version enabled? Maybe either of them is set to handle deeplinks by default and tries to handle the links of the other one (which it can't).

<img src="https://user-images.githubusercontent.com/26904189/96599629-67ed7b80-12f0-11eb-9f85-a2418eba4c73.gif" width="250" />

**Comment by tobiasrohloff** [comment]
On my Pixel it is only openHPI production and on the emulator openHPI debug.

**Comment by tobiasrohloff** [comment]
It works fine on an emulator with Android 10, so probably a bug with Android 11-only.

**Comment by bengelhaupt** [comment]
It has to do with https://developer.android.com/about/versions/11/privacy/package-visibility. I will try to find an acceptable fix.
