### ISSUE TITLE
Improve Error Message When Certificate Cannot Be Opened

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#287]
We got reports that users have problems opening certificates. They get error messages like "file broken/corrupt". We were not able to reproduce the issue for the same certificates, but most likely this is caused when no app is installed that can handle/open PDF files. Maybe we can simulate that behavior and improve the error message with a proper recommendation for action (e.g., install a PDF viewer) and/or provide alternative options (e.g., open in a file explorer, but here a proper fallback is required as well).

Think about a good strategy to guide the user to a proper solution. I expect that these users have the same issue for all PDF files, e.g., also for slides. Thus, we need to implement that in a reusable manner.

**Comment by tobiasrohloff** [comment]
We should probably use [Android 11's intent query to check if there is an app available](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-a-file) that can handle PDFs. I didn't check if there is another solution path on Android <= 10.

And we should probably do a similar check for [browser availability](https://developer.android.com/training/basics/intents/package-visibility-use-cases#check-browser-available) and [CustomTab availabilty](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-urls-custom-tabs) but in the scope of another ticket.

**Comment by bengelhaupt** [comment]
This is also a good opportunity to move all external file opening logic to a central place, preferably `IntentExtensions` or `FileExtensions`.

> We should probably use [Android 11's intent query to check if there is an app available](https://developer.android.com/training/basics/intents/package-visibility-use-cases#open-a-file) that can handle PDFs. I didn't check if there is another solution path on Android <= 10.

We can use our existing logic for querying intents in `IntentExtensions.createChooser(...)`. We just must not forget to add the `<queries>` declaration for Android 11.
