### ISSUE TITLE
Cannot Open LTI Exercises, again

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#300]
We have issues with LTI exercises again (older bug: #286).

It can be reproduced, for example, with this item:
https://open.hpi.de/courses/pythonjunior2020/items/rHiz0imat9JxB5Ih7K1PQ

<img src="https://user-images.githubusercontent.com/2922744/108189985-a580da80-7111-11eb-8d3d-4851d05ef24d.jpg" width="300" />

**Comment by tobiasrohloff** [comment]
@bengelhaupt what's the current status here? I think in our last discussion, you stated that the intent query for `https://` only includes the app itself and not the browser anymore.

**Comment by bengelhaupt** [comment]
It was that it somehow worked in the debug but not the production version. I just checked again and can't reproduce it anymore (Android 11 Physical + Android 10 Emulator).

**Comment by MrSerth** [comment]
Hm, I was able to reproduce it just now with the latest release version of the app in the Play Store.

![Screenshot_20210307-234031](https://user-images.githubusercontent.com/7300329/110257668-38899380-7f9f-11eb-8ba0-bfbf3dc097cd.png)
