### ISSUE TITLE
Cannot open forum thread linked in the video description

### ISSUE THREAD

**Issue by MrSerth** [openHPI/xikolo-android#323]
Some users [reported](https://open.hpi.de/courses/pythonjunior-schule2022/question/9991079f-d776-4853-b5fd-a52e6e11f520) that they cannot open a forum thread using the Android app. Instead, the app shows that no app is able to handle that target. We were able to reproduce this bug with [this item](https://open.hpi.de/courses/pythonjunior-schule2022/items/3jroaxAoaSSt77PGJo9gH8).

Android: 11 (MIUI 12.5.5)

<img src="https://user-images.githubusercontent.com/7300329/165182634-26530f67-e466-49de-b360-dad65a9e40c2.jpeg" width="300" />

**Comment by mathebox** [comment]
Fixed with version 3.9.3
