### ISSUE TITLE
Cannot Open LTI Exercises, again again

### ISSUE THREAD

**Issue by MrSerth** [openHPI/xikolo-android#329]
This issue is related to #286 and #300.

Learners still cannot open LTI exercises through the Android app.

It can be reproduced, for example, with this item:
https://open.hpi.de/courses/pythonjunior-schule2023/items/6SQn2hKJWZp1nUdoiTSr0b

|Error nous behavior (with Android)|Expected behavior (with iOS)|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/7300329/223481256-8fec2203-95eb-4f33-b379-3dd74c5fa191.jpeg" width="300" />|<img src="https://user-images.githubusercontent.com/7300329/223481919-fe67a4c4-a047-4f93-a5d8-40396a97ffda.PNG" width="300" />|

Android: 11
App: 3.8.2

**Comment by mathebox** [comment]
Fixed with version 3.9.3
