### ISSUE TITLE
Course Filter

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#58]
Filter courses for language or whitelisted classifier. Has to be merged with course search somehow.

**Comment by bengelhaupt** [comment]
I created a UI concept for course filtering.
What are possible filters and classifiers?

<img src="https://user-images.githubusercontent.com/26904189/77371518-c5721780-6d63-11ea-986b-54efa9f3b199.png" width="300px" /> <img src="https://user-images.githubusercontent.com/26904189/77371530-c99e3500-6d63-11ea-8bb7-b51f28a9263a.png" width="300px" />

<img src="https://user-images.githubusercontent.com/26904189/77371541-cf941600-6d63-11ea-915c-c137831f5267.png" width="300px" /> <img src="https://user-images.githubusercontent.com/26904189/77371544-d458ca00-6d63-11ea-8516-187595e56bef.png" width="300px" />

**Comment by tobiasrohloff** [comment]
Looks good! Please check the different course pages on the web app. Each platform has a different config for the filter dimensions. The values are exposed through the course API.
