### ISSUE TITLE
Course Teaser Video

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#61]
Add course teaser video to course info page.

**Comment by bengelhaupt** [comment]
I am rewriting our `VideoHelper` to a `VideoPlayerFragment` (takes a `VideoStream`) and `VideoFragment` (inherits from `VideoPlayerFragment`, takes a `Video` and provides offline playback and `Lanalytics` logging) which handle their own lifecycle and are extensible. I plan on having the `VideoPlayerFragment` placed on the course details screen right away, with autoplay disabled.
