### ISSUE TITLE
PreviewSeekBar for Videos

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/xikolo-android#81]
Let's check if we can integrate https://github.com/rubensousa/PreviewSeekBar for our videos.

**Comment by bensoftde** [comment]
@tobiasrohloff  The problem with this or previewing in general is, that no logic for creating a thumbnail at a specific position is given. Working around this might work well on video files saved locally but on videos played from the internet achieving this is more complicated.
The given library expects something like [this](https://bitdash-a.akamaihd.net/content/MI201109210084_1/thumbnails/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.jpg), previously generated thumbnails in a given interval for the whole video, but our API only provides one single thumbnail.

**Comment by tobiasrohloff** [comment]
@bensoftde [MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever) allows to extract bitmaps for frames. Maybe this could be used to extract them live.

**Comment by bensoftde** [comment]
@tobiasrohloff I will have a look on it, try it out and measure network usage.
